language: python
python:
  - "2.7"
install:
  - apt-get install rdiff-backup
  - pip install pep8
  - pip install pyflakes
  - pip install coverage
  - pip install coveralls
  - python setup.py install
before_script:
  - make verify
script:
  make test
after_success:
  coveralls
